spring:
  application:
    name: restaurant
#  datasource:
#    url: jdbc:h2:file:./data/gusRestaurant
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console


